name: Update RVI Data

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:  # Allow manual triggers too

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Create .env file
        run: |
          echo "ADJACENT_API_KEY=${{ secrets.ADJACENT_API_KEY }}" > .env
        
      - name: Run update script
        run: node scripts/fetch_and_transform_rvi.js
        
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add public/data snapshots
          git diff --quiet && git diff --staged --quiet || (git commit -m 'Update RVI data [automated]' && git push)
