name: Update RVI Data

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 30 minutes
  workflow_dispatch:  # Allow manual triggers too

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install root dependencies
        run: npm ci

      - name: Run RVI update script
        run: |
          cd scripts
          npm install
          echo "ADJACENT_API_KEY=${{ secrets.ADJACENT_API_KEY }}" > .env
          echo "SUPABASE_SERVICE_KEY=${{ secrets.SUPABASE_SERVICE_KEY }}" >> .env
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          node fetch_and_transform_rvi.js

      # Optional debugging block – enable if needed
      # - name: Debug Git Status
      #   run: |
      #     git status
      #     git diff
      #     git ls-files -m

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add public/data snapshots
          git diff --quiet && git diff --staged --quiet || (git commit -m 'Update RVI data [automated]' && git push)
